apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextjs-sample
  name: nextjs-sample
spec:
  replicas: 60
  selector:
    matchLabels:
      app: nextjs-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextjs-sample
    spec:
      containers:
      - image: {$AccountID}.dkr.ecr.ap-northeast-1.amazonaws.com/nextjs-sample:1.0.0
        name: nextjs-sample
        ports:
        - containerPort: 3000
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-sample-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: nextjs-sample
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-sample-alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nextjs-sample-svc
              port:
                number: 3000