apiVersion: eksctl.io/v1alpha5
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
metadata:
  name: Sandbox-EKS-Cluster
  region: ap-northeast-1
  version: "1.24"
nodeGroups:
- amiFamily: Bottlerocket
  bottlerocket:
    settings: {}
  # containerRuntime: dockerd
  desiredCapacity: 3
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: true
      appMesh: null
      appMeshPreview: null
      autoScaler: true
      awsLoadBalancerController: true
      certManager: false
      cloudWatch: true
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: true
  instanceSelector: {}
  instanceType: t3.small
  labels:
    alpha.eksctl.io/cluster-name: Sandbox-EKS-Cluster
    alpha.eksctl.io/nodegroup-name: Sandbox-EKS-NodeGroup
    role: workers
  name: Sandbox-EKS-NodeGroup
  privateNetworking: true
  securityGroups:
    withLocal: true
    withShared: true
  ssh:
    allow: false
  volumeIOPS: 3000
  volumeName: /dev/xvdb
  volumeSize: 20
  volumeThroughput: 125
  volumeType: gp3
privateCluster:
  enabled: false
  skipEndpointCreation: true
vpc:
  clusterEndpoints:
    # privateAccess: true
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Enable
  subnets:
    private:
      ap-northeast-1a:
        az: ap-northeast-1a
        id: subnet-0082612b34be454ad
      ap-northeast-1c:
        az: ap-northeast-1c
        id: subnet-01705fe278224dbc6