# https://eksctl.io/usage/schema/
apiVersion: eksctl.io/v1alpha5
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kind: ClusterConfig
metadata:
  name: Sandbox-EKS
  region: ap-northeast-1
  version: "1.24"
  tags:
    karpenter.sh/discovery: Sandbox-EKS

karpenter:
  version: 'v0.20.0' # Exact version must be provided
  createServiceAccount: true # default is false

managedNodeGroups:
- amiFamily: Bottlerocket
  bottlerocket:
    settings: {}
  # containerRuntime: dockerd
  desiredCapacity: 2
  minSize: 1
  maxSize: 10
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      # albIngress: true
      appMesh: null
      appMeshPreview: null
      autoScaler: true
      awsLoadBalancerController: true
      certManager: false
      cloudWatch: true
      ebs: true
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: true
      xRay: true
  instanceSelector: {}
  instanceType: t3.medium
  labels:
    alpha.eksctl.io/cluster-name: Sandbox-EKS-Cluster
    alpha.eksctl.io/nodegroup-name: Sandbox-EKS-NodeGroup
    role: workers
  name: Sandbox-EKS-NodeGroup
  privateNetworking: true
  # securityGroups:
  #   withLocal: true
  #   withShared: true
  ssh:
    allow: false
  volumeIOPS: 3000
  volumeName: /dev/xvdb
  volumeSize: 30
  volumeThroughput: 125
  volumeType: gp3
privateCluster:
  enabled: false
  skipEndpointCreation: true
vpc:
  clusterEndpoints:
    # privateAccess: true
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Enable
  subnets:
    private:
      ap-northeast-1a:
        az: ap-northeast-1a
        id: subnet-0082612b34be454ad
      ap-northeast-1c:
        az: ap-northeast-1c
        id: subnet-01705fe278224dbc6

addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest