apiVersion: eksctl.io/v1alpha5
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
managedNodeGroups:
- amiFamily: Bottlerocket
  bottlerocket:
    settings: {}
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      awsLoadBalancerController: true
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: t3.small
  labels:
    alpha.eksctl.io/cluster-name: EKS-Private-Sandbox-Cluster
    alpha.eksctl.io/nodegroup-name: managed-bottlerocket-ng
  maxSize: 2
  minSize: 1
  desiredCapacity: 2
  name: managed-bottlerocket-ng
  privateNetworking: true
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
    publicKeyPath: ""
  tags:
    alpha.eksctl.io/nodegroup-name: managed-bottlerocket-ng
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeName: /dev/xvdb
  volumeSize: 20
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: EKS-Private-Sandbox-Cluster
  region: ap-northeast-1
  version: "1.23"
privateCluster:
  enabled: true
  skipEndpointCreation: true
vpc:
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Disable
  subnets:
    private:
      ap-northeast-1a:
        az: ap-northeast-1a
        id: subnet-0561f71c8daef3904
      ap-northeast-1c:
        az: ap-northeast-1c
        id: subnet-020b46fe950624929